// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfdalyykgciomvgxpkjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmZGFseXlrZ2Npb212Z3hwa2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzEwNjEsImV4cCI6MjA2ODg0NzA2MX0.JcA98Zy1x_Mf3ZQWEI4tfY_jw7s8jrejZ6pKTUJFfeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});